apiVersion: v1
kind: Secret
metadata:
  name: mysite-secrets
stringData:
    SECRET_KEY: this-is-a-bad-key
    DJANGO_SUPERUSER_NAME: admin
    DJANGO_SUPERUSER_EMAIL: admin@admin.com
    DJANGO_SUPERUSER_PASSWORD: password
